# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a25ec798bd891c736100f23905512c66c758c73d8756f28905d5cab467b8cbbcd838c8ebf076cf234af66351c4a1dcaf9ba6b9c5e2b8e2511539f6dd5852ff5
  twitter_api_key:   AtN0GH8twjvbMYmHJCXfPV7WR
  twitter_api_secret:   itXj50Hwr75pWia4nVoKRELCOvdEIjooi7nOpMTIPc2Djj4quu
test:
  secret_key_base: 5b31f6b15b2f42a48d3e5297bc89596ca41cfa24f1c862c5b1a6e4ec50b2e3c1e3e24d1552a4c0548ed0c13b5ae8382fec8eb57bc428f12553953c29178eaea0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
